site_name: metaclass-registry
site_description: Zero-boilerplate metaclass-driven plugin registry system
site_author: Tristan Simas
site_url: https://metaclass-registry.readthedocs.io

repo_name: trissim/metaclass-registry
repo_url: https://github.com/trissim/metaclass-registry

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Patterns: patterns.md
  - API Reference: api.md
  - Examples:
    - Basic Registry: examples/basic.md
    - Secondary Registries: examples/secondary.md
    - Custom Key Extractors: examples/extractors.md
